🚧 workaround bug with cachyos-keyring
the following error indenticate that the entire keyrings for pacman are broken,
and that is resulting in broken keyrings after installing CachyOS with
the offline install option, which can be fixed manually with keyring
reset and locally signing CachyOS key:
```
(520/948) installing cachyos-keyring                                                                                                                                                           [-----------------------------------------------------------------------------------------------------------------------] 100%
error: config file /etc/pacman.d/cachyos-mirrorlist could not be read: No such file or directory
error parsing '/etc/pacman.conf'
mkdir: cannot create directory ‘’: No such file or directory
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
chmod: cannot access '/trustdb.gpg': No such file or directory
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: directory '/root/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/root/.gnupg/openpgp-revocs.d/593A5D4ECDB858180CAE1D681437E851B9F0620B.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
error: config file /etc/pacman.d/cachyos-mirrorlist could not be read: No such file or directory
error parsing '/etc/pacman.conf'
==> ERROR: You do not have sufficient permissions to read the pacman keyring.
==> Use 'pacman-key --init' to correct the keyring permissions.
error: config file /etc/pacman.d/cachyos-mirrorlist could not be read: No such file or directory
error parsing '/etc/pacman.conf'
==> ERROR: You do not have sufficient permissions to read the pacman keyring.
==> Use 'pacman-key --init' to correct the keyring permissions.
error: config file /etc/pacman.d/cachyos-mirrorlist could not be read: No such file or directory
error parsing '/etc/pacman.conf'
==> ERROR: You do not have sufficient permissions to read the pacman keyring.
==> Use 'pacman-key --init' to correct the keyring permissions.
error: command failed to execute correctly
```

was introduced with cleanup commit,
removing hardcoded mirrorlist

ref: 4750b7ffae95b0febb3ecefb77e11ba6984408e9